# Generated by Django 3.0.2 on 2020-01-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='schedule1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='subject',
            name='schedule2',
            field=models.CharField(default='Lun-20:00 a 22:00', max_length=30),
            preserve_default=False,
        ),
    ]
