# Generated by Django 3.0.2 on 2020-01-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20200118_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='schedule1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='schedule2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
