# Generated by Django 3.0.2 on 2020-01-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20200118_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='schedule1',
            field=models.CharField(default='No Schedule', max_length=30),
        ),
        migrations.AlterField(
            model_name='subject',
            name='schedule2',
            field=models.CharField(max_length=30, null='No Schedule'),
        ),
    ]
