# Generated by Django 3.0.2 on 2020-01-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20200118_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='timestamp',
        ),
    ]
