# Generated by Django 3.0.2 on 2020-01-19 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_remove_todo_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='result',
            new_name='grade',
        ),
    ]
