# Generated by Django 3.0.2 on 2020-01-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20200119_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('#f44336', 'red'), ('#e91e63', 'pink'), ('#2196f3', 'blue')], max_length=7, null=True),
        ),
    ]
