# Generated by Django 3.0.2 on 2020-01-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_subject_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
