# Generated by Django 3.0.2 on 2020-01-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_auto_20200122_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
