# Generated by Django 3.0.2 on 2020-01-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_auto_20200122_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='typeOf',
            field=models.CharField(default='Parcial', max_length=7),
        ),
    ]
