# Generated by Django 3.0.2 on 2020-01-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_subject_typeof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='typeOf',
        ),
        migrations.AddField(
            model_name='exam',
            name='typeOf',
            field=models.CharField(default='Parcial', max_length=7),
        ),
    ]
